import { useState, useRef } from "react";
import { useStore } from "../../app/store";
import { machineConnection } from "../../lib/machine/connection";
import { useEscapeClose } from "../../lib/hooks/useEscapeClose";
import { useFocusTrap } from "../../lib/hooks/useFocusTrap";

interface Props {
  open: boolean;
  onClose: () => void;
}

interface MaterialTestOptions {
  powerMin: number;
  powerMax: number;
  powerSteps: number;
  speedMin: number;
  speedMax: number;
  speedSteps: number;
  cellWidth: number;
  cellHeight: number;
  cellGap: number;
  mode: "cut" | "fill";
}

function generateMaterialTestGcode(opts: MaterialTestOptions, sValueMax: number): string {
  const lines: string[] = [];
  lines.push("; Material Test Grid -- Generated by Kerf");
  lines.push("G21 ; mm mode");
  lines.push("G90 ; absolute positioning");
  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0");
  lines.push("");

  const powers: number[] = [];
  for (let i = 0; i < opts.powerSteps; i++) {
    powers.push(
      opts.powerSteps === 1
        ? opts.powerMin
        : opts.powerMin + (opts.powerMax - opts.powerMin) * (i / (opts.powerSteps - 1)),
    );
  }

  const speeds: number[] = [];
  for (let i = 0; i < opts.speedSteps; i++) {
    speeds.push(
      opts.speedSteps === 1
        ? opts.speedMin
        : opts.speedMin + (opts.speedMax - opts.speedMin) * (i / (opts.speedSteps - 1)),
    );
  }

  const startX = 10; // mm offset from origin
  const startY = 10;

  for (let pi = 0; pi < powers.length; pi++) {
    for (let si = 0; si < speeds.length; si++) {
      const power = Math.round(powers[pi]);
      const speed = Math.round(speeds[si]);
      const sValue = Math.round((power / 100) * sValueMax);
      const feedRate = speed * 60; // mm/s to mm/min

      const cx = startX + si * (opts.cellWidth + opts.cellGap);
      // Y is inverted in G-code (origin bottom-left)
      const cy = startY + pi * (opts.cellHeight + opts.cellGap);

      lines.push(`; Cell P${power}% S${speed}mm/s`);

      if (opts.mode === "cut") {
        // Rectangle outline
        lines.push(`G0 X${cx.toFixed(3)} Y${cy.toFixed(3)}`);
        lines.push(`M4 S${sValue}`);
        lines.push(`G1 X${(cx + opts.cellWidth).toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${(cx + opts.cellWidth).toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${cx.toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${cx.toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push("M5");
      } else {
        // Filled rectangle (horizontal scan lines at 0.1mm interval)
        const interval = 0.1;
        let forward = true;
        let y = cy;
        while (y <= cy + opts.cellHeight) {
          const sx = forward ? cx : cx + opts.cellWidth;
          const ex = forward ? cx + opts.cellWidth : cx;
          lines.push(`G0 X${sx.toFixed(3)} Y${y.toFixed(3)}`);
          lines.push(`M4 S${sValue}`);
          lines.push(`G1 X${ex.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          lines.push("M5");
          y += interval;
          forward = !forward;
        }
      }
      lines.push("");
    }
  }

  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0 ; return home");
  lines.push("M2 ; program end");

  return lines.join("\n");
}

const inputStyle: React.CSSProperties = {
  background: "var(--bg-input)",
  border: "1px solid var(--border)",
  borderRadius: "var(--radius-sm)",
  color: "var(--text-primary)",
  padding: "4px 6px",
  fontSize: "12px",
  width: "70px",
  textAlign: "right",
};

const labelStyle: React.CSSProperties = {
  fontSize: "11px",
  color: "var(--text-secondary)",
  minWidth: "70px",
};

export function MaterialTestDialog({ open, onClose }: Props) {
  const [powerMin, setPowerMin] = useState(10);
  const [powerMax, setPowerMax] = useState(100);
  const [powerSteps, setPowerSteps] = useState(5);
  const [speedMin, setSpeedMin] = useState(50);
  const [speedMax, setSpeedMax] = useState(500);
  const [speedSteps, setSpeedSteps] = useState(5);
  const [cellWidth, setCellWidth] = useState(10);
  const [cellHeight, setCellHeight] = useState(10);
  const [cellGap, setCellGap] = useState(2);
  const [mode, setMode] = useState<"cut" | "fill">("cut");
  const jobRunning = useStore((s) => s.jobRunning);
  const grblSValueMax = useStore((s) => s.grblSValueMax);

  const dialogRef = useRef<HTMLDivElement>(null);
  useEscapeClose(open, onClose);
  useFocusTrap(dialogRef, open);

  if (!open) return null;

  const totalWidth = speedSteps * (cellWidth + cellGap) - cellGap + 10;
  const totalHeight = powerSteps * (cellHeight + cellGap) - cellGap + 10;
  const store = useStore.getState();
  const workspaceW = store.workspaceWidth;
  const workspaceH = store.workspaceHeight;
  const exceedsWorkspace = totalWidth > workspaceW || totalHeight > workspaceH;

  function handleGenerate(target: "clipboard" | "send") {
    const sMax = grblSValueMax;
    const gcode = generateMaterialTestGcode({
      powerMin, powerMax, powerSteps,
      speedMin, speedMax, speedSteps,
      cellWidth, cellHeight, cellGap, mode,
    }, sMax);

    if (target === "clipboard") {
      navigator.clipboard.writeText(gcode).then(() => {
        store.addConsoleLine(`Material test G-code copied (${gcode.split("\n").length} lines)`, "info");
      }).catch(() => { /* clipboard may be denied */ });
      onClose();
    } else {
      const connected = useStore.getState().machineConnected;
      if (!connected) {
        store.addConsoleLine("Machine not connected", "error");
        return;
      }
      // F18: block if a job is already running
      if (useStore.getState().jobRunning) {
        store.addConsoleLine("Cannot start material test while a job is running", "error");
        return;
      }
      // Send line by line
      const lines = gcode.split("\n").filter((l) => l.trim() && !l.startsWith(";"));
      store.addConsoleLine(`Sending material test (${lines.length} commands)...`, "info");
      store.setJobRunning(true);
      store.setSerialBusy(true);
      store.setJobProgress(0);

      (async () => {
        let aborted = false;
        for (let i = 0; i < lines.length; i++) {
          // F18: abort if jobRunning was cleared externally (e.g. emergency stop)
          if (!useStore.getState().jobRunning) break;
          const responses = await machineConnection.send(lines[i]);
          // Fix 4: abort on GRBL error or ALARM in any response line
          const errorLine = responses.find((r) => r.startsWith("error:") || r.startsWith("ALARM"));
          if (errorLine) {
            store.addConsoleLine(`Material test aborted: ${errorLine}`, "error");
            await machineConnection.send("M5");
            aborted = true;
            break;
          }
          store.setJobProgress((i + 1) / lines.length);
        }
        store.setSerialBusy(false);
        store.setJobRunning(false);
        store.setJobProgress(0);
        if (!aborted) {
          store.addConsoleLine("Material test complete", "info");
        }
      })();

      onClose();
    }
  }

  return (
    <div
      style={{
        position: "fixed", inset: 0, zIndex: 2000,
        display: "flex", alignItems: "center", justifyContent: "center",
        background: "rgba(0,0,0,0.5)",
      }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="material-test-dialog-title"
        style={{
          background: "var(--bg-panel)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-md)",
          boxShadow: "var(--shadow-panel)",
          padding: "20px",
          width: "380px",
          maxHeight: "90vh",
          overflow: "auto",
        }}
      >
        <div id="material-test-dialog-title" style={{ fontSize: "14px", fontWeight: 600, color: "var(--text-primary)", marginBottom: "16px" }}>
          Material Test Grid
        </div>

        {/* Power range */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Power (%)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Min</span>
            <input type="number" min="1" max="100" value={powerMin}
              onChange={(e) => setPowerMin(Math.max(1, Math.min(100, Number(e.target.value))))}
              style={inputStyle} />
            <span style={labelStyle}>Max</span>
            <input type="number" min="1" max="100" value={powerMax}
              onChange={(e) => setPowerMax(Math.max(1, Math.min(100, Number(e.target.value))))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Steps</span>
            <input type="number" min="1" max="20" value={powerSteps}
              onChange={(e) => setPowerSteps(Math.max(1, Math.min(20, Number(e.target.value))))}
              style={inputStyle} />
          </div>
        </div>

        {/* Speed range */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Speed (mm/s)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Min</span>
            <input type="number" min="1" max="10000" value={speedMin}
              onChange={(e) => setSpeedMin(Math.max(1, Number(e.target.value)))}
              style={inputStyle} />
            <span style={labelStyle}>Max</span>
            <input type="number" min="1" max="10000" value={speedMax}
              onChange={(e) => setSpeedMax(Math.max(1, Number(e.target.value)))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Steps</span>
            <input type="number" min="1" max="20" value={speedSteps}
              onChange={(e) => setSpeedSteps(Math.max(1, Math.min(20, Number(e.target.value))))}
              style={inputStyle} />
          </div>
        </div>

        {/* Cell size */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Cell Size (mm)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Width</span>
            <input type="number" min="2" max="50" value={cellWidth}
              onChange={(e) => setCellWidth(Math.max(2, Number(e.target.value)))}
              style={inputStyle} />
            <span style={labelStyle}>Height</span>
            <input type="number" min="2" max="50" value={cellHeight}
              onChange={(e) => setCellHeight(Math.max(2, Number(e.target.value)))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Gap</span>
            <input type="number" min="0" max="20" step="0.5" value={cellGap}
              onChange={(e) => setCellGap(Math.max(0, Number(e.target.value)))}
              style={inputStyle} />
          </div>
        </div>

        {/* Mode */}
        <div style={{ marginBottom: "16px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Mode
          </div>
          <div style={{ display: "flex", gap: "4px" }}>
            {(["cut", "fill"] as const).map((m) => (
              <button
                key={m}
                onClick={() => setMode(m)}
                style={{
                  flex: 1,
                  padding: "4px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: "pointer",
                  border: `1px solid ${mode === m ? "var(--accent)" : "var(--border)"}`,
                  background: mode === m ? "rgba(74,144,226,0.15)" : "transparent",
                  color: mode === m ? "var(--accent)" : "var(--text-muted)",
                  textTransform: "uppercase",
                }}
              >
                {m}
              </button>
            ))}
          </div>
        </div>

        {/* Grid size info */}
        <div style={{
          fontSize: "10px",
          color: exceedsWorkspace ? "var(--danger)" : "var(--text-muted)",
          marginBottom: "12px",
        }}>
          Grid: {powerSteps} x {speedSteps} = {powerSteps * speedSteps} cells,
          {" "}{totalWidth.toFixed(0)} x {totalHeight.toFixed(0)} mm
          {exceedsWorkspace && " -- exceeds workspace!"}
        </div>

        {/* Actions */}
        <div style={{ display: "flex", gap: "8px" }}>
          <button
            onClick={() => handleGenerate("send")}
            disabled={jobRunning}
            title={jobRunning ? "Cannot start while a job is running" : undefined}
            style={{
              flex: 1,
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "none",
              fontSize: "11px",
              fontWeight: 600,
              cursor: jobRunning ? "not-allowed" : "pointer",
              background: "rgba(74,226,138,0.2)",
              color: "var(--success)",
              opacity: jobRunning ? 0.4 : 1,
            }}
          >
            Send to Machine
          </button>
          <button
            onClick={() => handleGenerate("clipboard")}
            style={{
              flex: 1,
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              fontWeight: 600,
              cursor: "pointer",
              background: "transparent",
              color: "var(--text-secondary)",
            }}
          >
            Copy G-code
          </button>
          <button
            onClick={onClose}
            style={{
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              cursor: "pointer",
              background: "transparent",
              color: "var(--text-muted)",
            }}
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
