import { useState, useRef } from "react";
import { useStore } from "../../app/store";
import { streamJob } from "../../lib/machine/jobStream";
import { gcodeExtents, isWithinBounds } from "../../lib/machine/canStartJob";
import { useEscapeClose } from "../../lib/hooks/useEscapeClose";
import { useFocusTrap } from "../../lib/hooks/useFocusTrap";
import { effectiveMaxSpeed } from "../../lib/speedScale";
import { textToGcode } from "../../lib/machine/textGcode";

interface Props {
  open: boolean;
  onClose: () => void;
}

type PowerMode = "M3" | "M4";

interface MaterialTestOptions {
  powerMin: number;
  powerMax: number;
  powerSteps: number;
  speedMin: number;
  speedMax: number;
  speedSteps: number;
  cellWidth: number;
  cellHeight: number;
  cellGap: number;
  mode: "cut" | "fill";
  powerMode: PowerMode;
  labels: boolean;
  cutBorder: boolean;
}

const PRESETS: Record<string, MaterialTestOptions> = {
  "Quick Cut": {
    powerMin: 50, powerMax: 100, powerSteps: 4,
    speedMin: 300, speedMax: 800, speedSteps: 4,
    cellWidth: 8, cellHeight: 8, cellGap: 3,
    mode: "cut", powerMode: "M3", labels: true, cutBorder: true,
  },
  "Quick Engrave": {
    powerMin: 20, powerMax: 60, powerSteps: 4,
    speedMin: 3000, speedMax: 12000, speedSteps: 4,
    cellWidth: 8, cellHeight: 8, cellGap: 3,
    mode: "fill", powerMode: "M4", labels: true, cutBorder: true,
  },
  "Full Cut": {
    powerMin: 10, powerMax: 100, powerSteps: 10,
    speedMin: 100, speedMax: 1200, speedSteps: 10,
    cellWidth: 10, cellHeight: 10, cellGap: 3,
    mode: "cut", powerMode: "M3", labels: true, cutBorder: true,
  },
  "Full Engrave": {
    powerMin: 10, powerMax: 80, powerSteps: 10,
    speedMin: 1000, speedMax: 18000, speedSteps: 10,
    cellWidth: 10, cellHeight: 10, cellGap: 3,
    mode: "fill", powerMode: "M4", labels: true, cutBorder: true,
  },
};

async function generateMaterialTestGcode(opts: MaterialTestOptions, sValueMax: number): Promise<string> {
  const lines: string[] = [];
  lines.push("; Material Test Grid -- Generated by Kerf");
  lines.push("G21 ; mm mode");
  lines.push("G90 ; absolute positioning");
  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0");
  lines.push("");

  const powers: number[] = [];
  for (let i = 0; i < opts.powerSteps; i++) {
    powers.push(
      opts.powerSteps === 1
        ? opts.powerMin
        : opts.powerMin + (opts.powerMax - opts.powerMin) * (i / (opts.powerSteps - 1)),
    );
  }

  const speeds: number[] = [];
  for (let i = 0; i < opts.speedSteps; i++) {
    speeds.push(
      opts.speedSteps === 1
        ? opts.speedMin
        : opts.speedMin + (opts.speedMax - opts.speedMin) * (i / (opts.speedSteps - 1)),
    );
  }

  const labelMargin = opts.labels ? 5 : 0;
  const startX = 10 + labelMargin;
  const startY = 10 + labelMargin;

  // Column headers (speed values) — real text engraved above the grid
  if (opts.labels) {
    const labelS = Math.round(sValueMax * 0.12);
    const labelFeed = 3000;

    lines.push("; --- Column headers (speed) ---");
    for (let si = 0; si < speeds.length; si++) {
      const speed = Math.round(speeds[si]);
      const cx = startX + si * (opts.cellWidth + opts.cellGap);
      const ly = startY - 4; // 4mm above the grid — enough room for 2.5mm glyphs
      const labelLines = await textToGcode(
        `${speed}`, cx, ly, 2.5, labelS, labelFeed, opts.powerMode,
      );
      lines.push(...labelLines);
    }

    lines.push("; --- Row headers (power) ---");
    for (let pi = 0; pi < powers.length; pi++) {
      const power = Math.round(powers[pi]);
      const cy = startY + pi * (opts.cellHeight + opts.cellGap);
      const lx = startX - labelMargin; // left of the grid
      const labelLines = await textToGcode(
        `${power}%`, lx, cy + opts.cellHeight / 2 - 1, 2.5, labelS, labelFeed, opts.powerMode,
      );
      lines.push(...labelLines);
    }

    lines.push("");
  }

  for (let pi = 0; pi < powers.length; pi++) {
    for (let si = 0; si < speeds.length; si++) {
      const power = Math.round(powers[pi]);
      const speed = Math.round(speeds[si]);
      const sValue = Math.round((power / 100) * sValueMax);
      const feedRate = speed; // speed is already mm/min

      const cx = startX + si * (opts.cellWidth + opts.cellGap);
      // Y is inverted in G-code (origin bottom-left)
      const cy = startY + pi * (opts.cellHeight + opts.cellGap);

      lines.push(`; Cell P${power}% S${speed}mm/min`);

      if (opts.mode === "cut") {
        // Rectangle outline — power on once, off once
        lines.push(`G0 X${cx.toFixed(3)} Y${cy.toFixed(3)}`);
        lines.push(`${opts.powerMode} S${sValue}`);
        lines.push(`G1 X${(cx + opts.cellWidth).toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${(cx + opts.cellWidth).toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${cx.toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${cx.toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push("M5");
      } else {
        // Filled rectangle — continuous bidirectional sweep.
        // Power on ONCE before all scan lines, M5 ONCE after, no G0 between lines.
        // This eliminates the per-line M4/M5 accel spike pattern.
        const interval = 0.1;
        let forward = true;
        let y = cy;

        // Lead-in: position before power-on
        lines.push(`G0 X${cx.toFixed(3)} Y${y.toFixed(3)}`);
        lines.push(`${opts.powerMode} S${sValue}`);

        while (y <= cy + opts.cellHeight + 1e-9) {
          const ex = forward ? cx + opts.cellWidth : cx;
          lines.push(`G1 X${ex.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          y += interval;
          if (y <= cy + opts.cellHeight + 1e-9) {
            // Step to next line at feed rate (no G0, no M5 — continuous beam)
            forward = !forward;
            const nextX = forward ? cx : cx + opts.cellWidth;
            lines.push(`G1 X${nextX.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          } else {
            forward = !forward;
          }
        }

        lines.push("M5");
      }
      lines.push("");
    }
  }

  // Cut border — surrounds the entire grid for a reusable test card
  if (opts.cutBorder) {
    const gridW = opts.speedSteps * (opts.cellWidth + opts.cellGap) - opts.cellGap;
    const gridH = opts.powerSteps * (opts.cellHeight + opts.cellGap) - opts.cellGap;
    const margin = 3;
    const bx = startX - margin - labelMargin;
    const by = startY - margin - labelMargin;
    const bw = gridW + 2 * margin + labelMargin;
    const bh = gridH + 2 * margin + labelMargin;
    const borderS = sValueMax;
    const borderFeed = 200;
    lines.push("; --- Cut border (reusable test card) ---");
    lines.push(`G0 X${bx.toFixed(3)} Y${by.toFixed(3)}`);
    lines.push(`M3 S${borderS}`);
    lines.push(`G1 X${(bx + bw).toFixed(3)} Y${by.toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push(`G1 X${(bx + bw).toFixed(3)} Y${(by + bh).toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push(`G1 X${bx.toFixed(3)} Y${(by + bh).toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push(`G1 X${bx.toFixed(3)} Y${by.toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push("M5");
    lines.push("");
  }

  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0 ; return home");
  lines.push("M2 ; program end");

  return lines.join("\n");
}

function generateFrameGcode(totalWidth: number, totalHeight: number): string {
  const lines: string[] = [];
  lines.push("; Frame trace -- laser off");
  lines.push("G21");
  lines.push("G90");
  lines.push("M5");
  lines.push("G0 X10 Y10");
  lines.push(`G1 X${(10 + totalWidth).toFixed(3)} Y10 F3000`);
  lines.push(`G1 X${(10 + totalWidth).toFixed(3)} Y${(10 + totalHeight).toFixed(3)} F3000`);
  lines.push(`G1 X10 Y${(10 + totalHeight).toFixed(3)} F3000`);
  lines.push("G1 X10 Y10 F3000");
  lines.push("G0 X0 Y0");
  return lines.join("\n");
}

const inputStyle: React.CSSProperties = {
  background: "var(--bg-input)",
  border: "1px solid var(--border)",
  borderRadius: "var(--radius-sm)",
  color: "var(--text-primary)",
  padding: "4px 6px",
  fontSize: "12px",
  width: "70px",
  textAlign: "right",
};

const labelStyle: React.CSSProperties = {
  fontSize: "11px",
  color: "var(--text-secondary)",
  minWidth: "70px",
};

export function MaterialTestDialog({ open, onClose }: Props) {
  const [powerMin, setPowerMin] = useState(10);
  const [powerMax, setPowerMax] = useState(100);
  const [powerSteps, setPowerSteps] = useState(5);
  const [speedMin, setSpeedMin] = useState(300);
  const [speedMax, setSpeedMax] = useState(3000);
  const [speedSteps, setSpeedSteps] = useState(5);
  const [cellWidth, setCellWidth] = useState(10);
  const [cellHeight, setCellHeight] = useState(10);
  const [cellGap, setCellGap] = useState(2);
  const [mode, setMode] = useState<"cut" | "fill">("cut");
  const [powerMode, setPowerMode] = useState<PowerMode>("M4");
  const [labels, setLabels] = useState(true);
  const [cutBorder, setCutBorder] = useState(true);

  // Scalar selectors only — never return a new object/array (React Error 185)
  const jobRunning = useStore((s) => s.jobRunning);
  const grblSValueMax = useStore((s) => s.grblSValueMax);
  const grblMaxFeedRateX = useStore((s) => s.grblMaxFeedRateX);
  const grblMaxFeedRateY = useStore((s) => s.grblMaxFeedRateY);
  const grblLaserMode = useStore((s) => s.grblLaserMode);
  // A5: subscribe to workspace dimensions reactively (not render-time getState)
  const workspaceW = useStore((s) => s.workspaceWidth);
  const workspaceH = useStore((s) => s.workspaceHeight);
  const machineConnected = useStore((s) => s.machineConnected);
  const machineState = useStore((s) => s.machineState);
  const effectiveSpeedMax = effectiveMaxSpeed(grblMaxFeedRateX, grblMaxFeedRateY);

  const dialogRef = useRef<HTMLDivElement>(null);
  useEscapeClose(open, onClose);
  useFocusTrap(dialogRef, open);

  if (!open) return null;

  const gridWidth = speedSteps * (cellWidth + cellGap) - cellGap;
  const gridHeight = powerSteps * (cellHeight + cellGap) - cellGap;
  const lm = labels ? 5 : 0;
  const bm = cutBorder ? 3 : 0;
  const totalWidth = gridWidth + lm + 2 * bm;
  const totalHeight = gridHeight + lm + 2 * bm;
  // A5: exceedsWorkspace from reactive selectors (no render-time getState)
  const exceedsWorkspace = (totalWidth + 10) > workspaceW || (totalHeight + 10) > workspaceH;

  function applyPreset(name: string) {
    const p = PRESETS[name];
    if (!p) return;
    setPowerMin(p.powerMin);
    setPowerMax(p.powerMax);
    setPowerSteps(p.powerSteps);
    setSpeedMin(p.speedMin);
    setSpeedMax(p.speedMax);
    setSpeedSteps(p.speedSteps);
    setCellWidth(p.cellWidth);
    setCellHeight(p.cellHeight);
    setCellGap(p.cellGap);
    setMode(p.mode);
    setPowerMode(p.powerMode);
    setLabels(p.labels);
    setCutBorder(p.cutBorder);
  }

  async function handleGenerate(target: "clipboard" | "send") {
    const gcode = await generateMaterialTestGcode({
      powerMin, powerMax, powerSteps,
      speedMin, speedMax, speedSteps,
      cellWidth, cellHeight, cellGap, mode, powerMode, labels, cutBorder,
    }, grblSValueMax);

    if (target === "clipboard") {
      const store = useStore.getState();
      navigator.clipboard.writeText(gcode).then(() => {
        store.addConsoleLine(`Material test G-code copied (${gcode.split("\n").length} lines)`, "info");
      }).catch(() => { /* clipboard may be denied */ });
      onClose();
    } else {
      const state = useStore.getState();
      if (!state.machineConnected) {
        state.addConsoleLine("Machine not connected", "error");
        return;
      }
      if (state.jobRunning) {
        state.addConsoleLine("Cannot start material test while a job is running", "error");
        return;
      }
      // A5: hard gate — bounds check generated G-code before sending
      const ext = gcodeExtents(gcode);
      if (ext && !isWithinBounds(ext, state.workspaceWidth, state.workspaceHeight)) {
        state.addConsoleLine(
          "Material test blocked: grid extends outside workspace bounds. Reduce steps or cell size.",
          "error",
        );
        return; // dialog stays open
      }
      const lines = gcode.split("\n").filter((l) => l.trim() && !l.startsWith(";"));
      state.addConsoleLine(`Sending material test (${lines.length} commands)...`, "info");
      state.setJobRunning(true);
      state.setJobProgress(0);
      streamJob(gcode, { label: "Material test" }); // fire-and-forget: dialog closes
      onClose();
    }
  }

  function handleFrame() {
    const state = useStore.getState();
    if (!state.machineConnected) {
      state.addConsoleLine("Machine not connected", "error");
      return;
    }
    if (state.jobRunning) {
      state.addConsoleLine("Cannot start frame while a job is running", "error");
      return;
    }
    const gcode = generateFrameGcode(totalWidth, totalHeight);
    // A5: hard gate — bounds check frame G-code before sending
    const ext = gcodeExtents(gcode);
    if (ext && !isWithinBounds(ext, state.workspaceWidth, state.workspaceHeight)) {
      state.addConsoleLine(
        "Frame blocked: grid extends outside workspace bounds. Reduce steps or cell size.",
        "error",
      );
      return; // dialog stays open
    }
    const lines = gcode.split("\n").filter((l) => l.trim() && !l.startsWith(";"));
    state.addConsoleLine(`Sending frame (${lines.length} commands)...`, "info");
    state.setJobRunning(true);
    state.setJobProgress(0);
    streamJob(gcode, { label: "Frame" }); // fire-and-forget: dialog closes
    onClose();
  }

  const showLaserWarning = powerMode === "M4" && !grblLaserMode;

  return (
    <div
      style={{
        position: "fixed", inset: 0, zIndex: 2000,
        display: "flex", alignItems: "center", justifyContent: "center",
        background: "rgba(0,0,0,0.5)",
      }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="material-test-dialog-title"
        style={{
          background: "var(--bg-panel)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-md)",
          boxShadow: "var(--shadow-panel)",
          padding: "20px",
          width: "380px",
          maxHeight: "90vh",
          overflow: "auto",
        }}
      >
        <div id="material-test-dialog-title" style={{ fontSize: "14px", fontWeight: 600, color: "var(--text-primary)", marginBottom: "12px" }}>
          Material Test Grid
        </div>

        {/* $32=0 warning banner */}
        {showLaserWarning && (
          <div style={{
            background: "rgba(226,167,74,0.15)",
            border: "1px solid rgba(226,167,74,0.4)",
            borderRadius: "var(--radius-sm)",
            padding: "8px 10px",
            marginBottom: "12px",
            fontSize: "11px",
            color: "var(--warning, #e2a74a)",
            lineHeight: 1.4,
          }}>
            Laser mode ($32) is disabled -- M4 won't fire. Enable with $32=1 in the console.
          </div>
        )}

        {/* Presets */}
        <div style={{ marginBottom: "14px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Presets
          </div>
          <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
            {Object.keys(PRESETS).map((name) => (
              <button
                key={name}
                onClick={() => applyPreset(name)}
                style={{
                  padding: "3px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 500,
                  cursor: "pointer",
                  border: "1px solid var(--border)",
                  background: "transparent",
                  color: "var(--text-secondary)",
                }}
              >
                {name}
              </button>
            ))}
          </div>
        </div>

        {/* Power range */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Power (%)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Min</span>
            <input type="number" min="1" max="100" value={powerMin}
              onChange={(e) => setPowerMin(Math.max(1, Math.min(100, Number(e.target.value))))}
              style={inputStyle} />
            <span style={labelStyle}>Max</span>
            <input type="number" min="1" max="100" value={powerMax}
              onChange={(e) => setPowerMax(Math.max(1, Math.min(100, Number(e.target.value))))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Steps</span>
            <input type="number" min="1" max="20" value={powerSteps}
              onChange={(e) => setPowerSteps(Math.max(1, Math.min(20, Number(e.target.value))))}
              style={inputStyle} />
          </div>
        </div>

        {/* Speed range */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Speed (mm/min)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Min</span>
            <input type="number" min="1" max={effectiveSpeedMax} value={speedMin}
              onChange={(e) => setSpeedMin(Math.max(1, Math.min(effectiveSpeedMax, Number(e.target.value))))}
              style={inputStyle} />
            <span style={labelStyle}>Max</span>
            <input type="number" min="1" max={effectiveSpeedMax} value={speedMax}
              onChange={(e) => setSpeedMax(Math.max(1, Math.min(effectiveSpeedMax, Number(e.target.value))))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Steps</span>
            <input type="number" min="1" max="20" value={speedSteps}
              onChange={(e) => setSpeedSteps(Math.max(1, Math.min(20, Number(e.target.value))))}
              style={inputStyle} />
          </div>
        </div>

        {/* Cell size */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Cell Size (mm)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Width</span>
            <input type="number" min="2" max="50" value={cellWidth}
              onChange={(e) => setCellWidth(Math.max(2, Number(e.target.value)))}
              style={inputStyle} />
            <span style={labelStyle}>Height</span>
            <input type="number" min="2" max="50" value={cellHeight}
              onChange={(e) => setCellHeight(Math.max(2, Number(e.target.value)))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Gap</span>
            <input type="number" min="0" max="20" step="0.5" value={cellGap}
              onChange={(e) => setCellGap(Math.max(0, Number(e.target.value)))}
              style={inputStyle} />
          </div>
        </div>

        {/* Mode + Power mode */}
        <div style={{ marginBottom: "16px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Mode
          </div>
          <div style={{ display: "flex", gap: "4px" }}>
            {(["cut", "fill"] as const).map((m) => (
              <button
                key={m}
                onClick={() => setMode(m)}
                style={{
                  flex: 1,
                  padding: "4px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: "pointer",
                  border: `1px solid ${mode === m ? "var(--accent)" : "var(--border)"}`,
                  background: mode === m ? "rgba(74,144,226,0.15)" : "transparent",
                  color: mode === m ? "var(--accent)" : "var(--text-muted)",
                  textTransform: "uppercase",
                }}
              >
                {m}
              </button>
            ))}
            <div style={{ width: "1px", background: "var(--border)", margin: "0 4px" }} />
            {(["M3", "M4"] as const).map((pm) => (
              <button
                key={pm}
                onClick={() => setPowerMode(pm)}
                title={pm === "M3" ? "Constant power" : "Variable power (laser mode)"}
                style={{
                  flex: 1,
                  padding: "4px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: "pointer",
                  border: `1px solid ${powerMode === pm ? "var(--accent)" : "var(--border)"}`,
                  background: powerMode === pm ? "rgba(74,144,226,0.15)" : "transparent",
                  color: powerMode === pm ? "var(--accent)" : "var(--text-muted)",
                  textTransform: "uppercase",
                }}
              >
                {pm === "M3" ? "M3 Const" : "M4 Var"}
              </button>
            ))}
          </div>
        </div>

        {/* Options */}
        <div style={{ display: "flex", gap: "12px", marginBottom: "12px" }}>
          <label style={{ display: "flex", alignItems: "center", gap: "4px", fontSize: "11px", color: "var(--text-secondary)", cursor: "pointer" }}>
            <input type="checkbox" checked={labels} onChange={(e) => setLabels(e.target.checked)} />
            Labels
          </label>
          <label style={{ display: "flex", alignItems: "center", gap: "4px", fontSize: "11px", color: "var(--text-secondary)", cursor: "pointer" }}>
            <input type="checkbox" checked={cutBorder} onChange={(e) => setCutBorder(e.target.checked)} />
            Cut border
          </label>
        </div>

        {/* Grid size info */}
        <div style={{
          fontSize: "10px",
          color: exceedsWorkspace ? "var(--danger)" : "var(--text-muted)",
          marginBottom: "12px",
        }}>
          Grid: {powerSteps} x {speedSteps} = {powerSteps * speedSteps} cells,
          {" "}{totalWidth.toFixed(0)} x {totalHeight.toFixed(0)} mm
          {exceedsWorkspace && " -- exceeds workspace!"}
        </div>

        {/* Actions — A5: Send/Frame disabled when exceeds bounds or not idle */}
        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
          {(() => {
            const sendDisabled = jobRunning || exceedsWorkspace || !machineConnected || (machineState !== "idle" && machineState !== "disconnected");
            const sendTitle = exceedsWorkspace
              ? "Grid exceeds workspace bounds"
              : jobRunning
                ? "Cannot start while a job is running"
                : !machineConnected
                  ? "Machine not connected"
                  : undefined;
            return (
              <button
                onClick={() => handleGenerate("send")}
                disabled={sendDisabled}
                title={sendTitle}
                style={{
                  flex: "1 1 auto",
                  padding: "6px 12px",
                  borderRadius: "var(--radius-sm)",
                  border: "none",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: sendDisabled ? "not-allowed" : "pointer",
                  background: "rgba(74,226,138,0.2)",
                  color: "var(--success)",
                  opacity: sendDisabled ? 0.4 : 1,
                }}
              >
                Send to Machine
              </button>
            );
          })()}
          {(() => {
            const frameDisabled = jobRunning || exceedsWorkspace || !machineConnected || machineState !== "idle";
            const frameTitle = exceedsWorkspace
              ? "Grid exceeds workspace bounds"
              : jobRunning
                ? "Cannot frame while a job is running"
                : !machineConnected
                  ? "Machine not connected"
                  : "Trace the grid outline without firing the laser";
            return (
              <button
                onClick={handleFrame}
                disabled={frameDisabled}
                title={frameTitle}
                style={{
                  flex: "1 1 auto",
                  padding: "6px 12px",
                  borderRadius: "var(--radius-sm)",
                  border: "1px solid var(--border)",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: frameDisabled ? "not-allowed" : "pointer",
                  background: "transparent",
                  color: "var(--text-secondary)",
                  opacity: frameDisabled ? 0.4 : 1,
                }}
              >
                Frame
              </button>
            );
          })()}
          <button
            onClick={() => handleGenerate("clipboard")}
            style={{
              flex: "1 1 auto",
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              fontWeight: 600,
              cursor: "pointer",
              background: "transparent",
              color: "var(--text-secondary)",
            }}
          >
            Copy G-code
          </button>
          <button
            onClick={onClose}
            style={{
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              cursor: "pointer",
              background: "transparent",
              color: "var(--text-muted)",
            }}
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
