import { useState, useRef } from "react";
import { useStore } from "../../app/store";
import { machineConnection } from "../../lib/machine/connection";
import { useEscapeClose } from "../../lib/hooks/useEscapeClose";
import { useFocusTrap } from "../../lib/hooks/useFocusTrap";
import { effectiveMaxSpeed } from "../../lib/speedScale";

interface Props {
  open: boolean;
  onClose: () => void;
}

type PowerMode = "M3" | "M4";

interface MaterialTestOptions {
  powerMin: number;
  powerMax: number;
  powerSteps: number;
  speedMin: number;
  speedMax: number;
  speedSteps: number;
  cellWidth: number;
  cellHeight: number;
  cellGap: number;
  mode: "cut" | "fill";
  powerMode: PowerMode;
}

const PRESETS: Record<string, MaterialTestOptions> = {
  "Quick Cut": {
    powerMin: 50, powerMax: 100, powerSteps: 4,
    speedMin: 300, speedMax: 800, speedSteps: 4,
    cellWidth: 8, cellHeight: 8, cellGap: 1.5,
    mode: "cut", powerMode: "M3",
  },
  "Quick Engrave": {
    powerMin: 20, powerMax: 60, powerSteps: 4,
    speedMin: 3000, speedMax: 12000, speedSteps: 4,
    cellWidth: 8, cellHeight: 8, cellGap: 1.5,
    mode: "fill", powerMode: "M4",
  },
  "Full Cut": {
    powerMin: 10, powerMax: 100, powerSteps: 10,
    speedMin: 100, speedMax: 1200, speedSteps: 10,
    cellWidth: 10, cellHeight: 10, cellGap: 2,
    mode: "cut", powerMode: "M3",
  },
  "Full Engrave": {
    powerMin: 10, powerMax: 80, powerSteps: 10,
    speedMin: 1000, speedMax: 18000, speedSteps: 10,
    cellWidth: 10, cellHeight: 10, cellGap: 2,
    mode: "fill", powerMode: "M4",
  },
};

function generateMaterialTestGcode(opts: MaterialTestOptions, sValueMax: number): string {
  const lines: string[] = [];
  lines.push("; Material Test Grid -- Generated by Kerf");
  lines.push("G21 ; mm mode");
  lines.push("G90 ; absolute positioning");
  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0");
  lines.push("");

  const powers: number[] = [];
  for (let i = 0; i < opts.powerSteps; i++) {
    powers.push(
      opts.powerSteps === 1
        ? opts.powerMin
        : opts.powerMin + (opts.powerMax - opts.powerMin) * (i / (opts.powerSteps - 1)),
    );
  }

  const speeds: number[] = [];
  for (let i = 0; i < opts.speedSteps; i++) {
    speeds.push(
      opts.speedSteps === 1
        ? opts.speedMin
        : opts.speedMin + (opts.speedMax - opts.speedMin) * (i / (opts.speedSteps - 1)),
    );
  }

  const startX = 10; // mm offset from origin
  const startY = 10;

  for (let pi = 0; pi < powers.length; pi++) {
    for (let si = 0; si < speeds.length; si++) {
      const power = Math.round(powers[pi]);
      const speed = Math.round(speeds[si]);
      const sValue = Math.round((power / 100) * sValueMax);
      const feedRate = speed; // speed is already mm/min

      const cx = startX + si * (opts.cellWidth + opts.cellGap);
      // Y is inverted in G-code (origin bottom-left)
      const cy = startY + pi * (opts.cellHeight + opts.cellGap);

      lines.push(`; Cell P${power}% S${speed}mm/min`);

      if (opts.mode === "cut") {
        // Rectangle outline — power on once, off once
        lines.push(`G0 X${cx.toFixed(3)} Y${cy.toFixed(3)}`);
        lines.push(`${opts.powerMode} S${sValue}`);
        lines.push(`G1 X${(cx + opts.cellWidth).toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${(cx + opts.cellWidth).toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${cx.toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`);
        lines.push(`G1 X${cx.toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push("M5");
      } else {
        // Filled rectangle — continuous bidirectional sweep.
        // Power on ONCE before all scan lines, M5 ONCE after, no G0 between lines.
        // This eliminates the per-line M4/M5 accel spike pattern.
        const interval = 0.1;
        let forward = true;
        let y = cy;

        // Lead-in: position before power-on
        lines.push(`G0 X${cx.toFixed(3)} Y${y.toFixed(3)}`);
        lines.push(`${opts.powerMode} S${sValue}`);

        while (y <= cy + opts.cellHeight + 1e-9) {
          const ex = forward ? cx + opts.cellWidth : cx;
          lines.push(`G1 X${ex.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          y += interval;
          if (y <= cy + opts.cellHeight + 1e-9) {
            // Step to next line at feed rate (no G0, no M5 — continuous beam)
            forward = !forward;
            const nextX = forward ? cx : cx + opts.cellWidth;
            lines.push(`G1 X${nextX.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          } else {
            forward = !forward;
          }
        }

        lines.push("M5");
      }
      lines.push("");
    }
  }

  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0 ; return home");
  lines.push("M2 ; program end");

  return lines.join("\n");
}

function generateFrameGcode(totalWidth: number, totalHeight: number): string {
  const lines: string[] = [];
  lines.push("; Frame trace -- laser off");
  lines.push("G21");
  lines.push("G90");
  lines.push("M5");
  lines.push("G0 X10 Y10");
  lines.push(`G1 X${(10 + totalWidth).toFixed(3)} Y10 F3000`);
  lines.push(`G1 X${(10 + totalWidth).toFixed(3)} Y${(10 + totalHeight).toFixed(3)} F3000`);
  lines.push(`G1 X10 Y${(10 + totalHeight).toFixed(3)} F3000`);
  lines.push("G1 X10 Y10 F3000");
  lines.push("G0 X0 Y0");
  return lines.join("\n");
}

const inputStyle: React.CSSProperties = {
  background: "var(--bg-input)",
  border: "1px solid var(--border)",
  borderRadius: "var(--radius-sm)",
  color: "var(--text-primary)",
  padding: "4px 6px",
  fontSize: "12px",
  width: "70px",
  textAlign: "right",
};

const labelStyle: React.CSSProperties = {
  fontSize: "11px",
  color: "var(--text-secondary)",
  minWidth: "70px",
};

export function MaterialTestDialog({ open, onClose }: Props) {
  const [powerMin, setPowerMin] = useState(10);
  const [powerMax, setPowerMax] = useState(100);
  const [powerSteps, setPowerSteps] = useState(5);
  const [speedMin, setSpeedMin] = useState(300);
  const [speedMax, setSpeedMax] = useState(3000);
  const [speedSteps, setSpeedSteps] = useState(5);
  const [cellWidth, setCellWidth] = useState(10);
  const [cellHeight, setCellHeight] = useState(10);
  const [cellGap, setCellGap] = useState(2);
  const [mode, setMode] = useState<"cut" | "fill">("cut");
  const [powerMode, setPowerMode] = useState<PowerMode>("M4");

  // Scalar selectors only — never return a new object/array (React Error 185)
  const jobRunning = useStore((s) => s.jobRunning);
  const grblSValueMax = useStore((s) => s.grblSValueMax);
  const grblMaxFeedRateX = useStore((s) => s.grblMaxFeedRateX);
  const grblMaxFeedRateY = useStore((s) => s.grblMaxFeedRateY);
  const grblLaserMode = useStore((s) => s.grblLaserMode);
  const effectiveSpeedMax = effectiveMaxSpeed(grblMaxFeedRateX, grblMaxFeedRateY);

  const dialogRef = useRef<HTMLDivElement>(null);
  useEscapeClose(open, onClose);
  useFocusTrap(dialogRef, open);

  if (!open) return null;

  const totalWidth = speedSteps * (cellWidth + cellGap) - cellGap;
  const totalHeight = powerSteps * (cellHeight + cellGap) - cellGap;
  const store = useStore.getState();
  const workspaceW = store.workspaceWidth;
  const workspaceH = store.workspaceHeight;
  const exceedsWorkspace = (totalWidth + 10) > workspaceW || (totalHeight + 10) > workspaceH;

  function applyPreset(name: string) {
    const p = PRESETS[name];
    if (!p) return;
    setPowerMin(p.powerMin);
    setPowerMax(p.powerMax);
    setPowerSteps(p.powerSteps);
    setSpeedMin(p.speedMin);
    setSpeedMax(p.speedMax);
    setSpeedSteps(p.speedSteps);
    setCellWidth(p.cellWidth);
    setCellHeight(p.cellHeight);
    setCellGap(p.cellGap);
    setMode(p.mode);
    setPowerMode(p.powerMode);
  }

  async function sendLines(gcode: string, label: string) {
    const connected = useStore.getState().machineConnected;
    if (!connected) {
      store.addConsoleLine("Machine not connected", "error");
      return;
    }
    if (useStore.getState().jobRunning) {
      store.addConsoleLine(`Cannot start ${label} while a job is running`, "error");
      return;
    }
    const lines = gcode.split("\n").filter((l) => l.trim() && !l.startsWith(";"));
    store.addConsoleLine(`Sending ${label} (${lines.length} commands)...`, "info");
    store.setJobRunning(true);
    store.setSerialBusy(true);
    store.setJobProgress(0);

    let aborted = false;
    for (let i = 0; i < lines.length; i++) {
      if (!useStore.getState().jobRunning) break;
      const responses = await machineConnection.send(lines[i]);
      const errorLine = responses.find((r) => r.startsWith("error:") || r.startsWith("ALARM"));
      if (errorLine) {
        store.addConsoleLine(`${label} aborted: ${errorLine}`, "error");
        await machineConnection.send("M5");
        aborted = true;
        break;
      }
      store.setJobProgress((i + 1) / lines.length);
    }
    store.setSerialBusy(false);
    store.setJobRunning(false);
    store.setJobProgress(0);
    if (!aborted) {
      store.addConsoleLine(`${label} complete`, "info");
    }
  }

  function handleGenerate(target: "clipboard" | "send") {
    const gcode = generateMaterialTestGcode({
      powerMin, powerMax, powerSteps,
      speedMin, speedMax, speedSteps,
      cellWidth, cellHeight, cellGap, mode, powerMode,
    }, grblSValueMax);

    if (target === "clipboard") {
      navigator.clipboard.writeText(gcode).then(() => {
        store.addConsoleLine(`Material test G-code copied (${gcode.split("\n").length} lines)`, "info");
      }).catch(() => { /* clipboard may be denied */ });
      onClose();
    } else {
      sendLines(gcode, "material test");
      onClose();
    }
  }

  function handleFrame() {
    const gcode = generateFrameGcode(totalWidth, totalHeight);
    sendLines(gcode, "frame");
    onClose();
  }

  const showLaserWarning = powerMode === "M4" && !grblLaserMode;

  return (
    <div
      style={{
        position: "fixed", inset: 0, zIndex: 2000,
        display: "flex", alignItems: "center", justifyContent: "center",
        background: "rgba(0,0,0,0.5)",
      }}
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="material-test-dialog-title"
        style={{
          background: "var(--bg-panel)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-md)",
          boxShadow: "var(--shadow-panel)",
          padding: "20px",
          width: "380px",
          maxHeight: "90vh",
          overflow: "auto",
        }}
      >
        <div id="material-test-dialog-title" style={{ fontSize: "14px", fontWeight: 600, color: "var(--text-primary)", marginBottom: "12px" }}>
          Material Test Grid
        </div>

        {/* $32=0 warning banner */}
        {showLaserWarning && (
          <div style={{
            background: "rgba(226,167,74,0.15)",
            border: "1px solid rgba(226,167,74,0.4)",
            borderRadius: "var(--radius-sm)",
            padding: "8px 10px",
            marginBottom: "12px",
            fontSize: "11px",
            color: "var(--warning, #e2a74a)",
            lineHeight: 1.4,
          }}>
            Laser mode ($32) is disabled -- M4 won't fire. Enable with $32=1 in the console.
          </div>
        )}

        {/* Presets */}
        <div style={{ marginBottom: "14px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Presets
          </div>
          <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
            {Object.keys(PRESETS).map((name) => (
              <button
                key={name}
                onClick={() => applyPreset(name)}
                style={{
                  padding: "3px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 500,
                  cursor: "pointer",
                  border: "1px solid var(--border)",
                  background: "transparent",
                  color: "var(--text-secondary)",
                }}
              >
                {name}
              </button>
            ))}
          </div>
        </div>

        {/* Power range */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Power (%)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Min</span>
            <input type="number" min="1" max="100" value={powerMin}
              onChange={(e) => setPowerMin(Math.max(1, Math.min(100, Number(e.target.value))))}
              style={inputStyle} />
            <span style={labelStyle}>Max</span>
            <input type="number" min="1" max="100" value={powerMax}
              onChange={(e) => setPowerMax(Math.max(1, Math.min(100, Number(e.target.value))))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Steps</span>
            <input type="number" min="1" max="20" value={powerSteps}
              onChange={(e) => setPowerSteps(Math.max(1, Math.min(20, Number(e.target.value))))}
              style={inputStyle} />
          </div>
        </div>

        {/* Speed range */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Speed (mm/min)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Min</span>
            <input type="number" min="1" max={effectiveSpeedMax} value={speedMin}
              onChange={(e) => setSpeedMin(Math.max(1, Math.min(effectiveSpeedMax, Number(e.target.value))))}
              style={inputStyle} />
            <span style={labelStyle}>Max</span>
            <input type="number" min="1" max={effectiveSpeedMax} value={speedMax}
              onChange={(e) => setSpeedMax(Math.max(1, Math.min(effectiveSpeedMax, Number(e.target.value))))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Steps</span>
            <input type="number" min="1" max="20" value={speedSteps}
              onChange={(e) => setSpeedSteps(Math.max(1, Math.min(20, Number(e.target.value))))}
              style={inputStyle} />
          </div>
        </div>

        {/* Cell size */}
        <div style={{ marginBottom: "12px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Cell Size (mm)
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <span style={labelStyle}>Width</span>
            <input type="number" min="2" max="50" value={cellWidth}
              onChange={(e) => setCellWidth(Math.max(2, Number(e.target.value)))}
              style={inputStyle} />
            <span style={labelStyle}>Height</span>
            <input type="number" min="2" max="50" value={cellHeight}
              onChange={(e) => setCellHeight(Math.max(2, Number(e.target.value)))}
              style={inputStyle} />
          </div>
          <div style={{ display: "flex", gap: "8px", alignItems: "center", marginTop: "4px" }}>
            <span style={labelStyle}>Gap</span>
            <input type="number" min="0" max="20" step="0.5" value={cellGap}
              onChange={(e) => setCellGap(Math.max(0, Number(e.target.value)))}
              style={inputStyle} />
          </div>
        </div>

        {/* Mode + Power mode */}
        <div style={{ marginBottom: "16px" }}>
          <div style={{ fontSize: "10px", color: "var(--text-muted)", textTransform: "uppercase", marginBottom: "6px", fontWeight: 600 }}>
            Mode
          </div>
          <div style={{ display: "flex", gap: "4px" }}>
            {(["cut", "fill"] as const).map((m) => (
              <button
                key={m}
                onClick={() => setMode(m)}
                style={{
                  flex: 1,
                  padding: "4px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: "pointer",
                  border: `1px solid ${mode === m ? "var(--accent)" : "var(--border)"}`,
                  background: mode === m ? "rgba(74,144,226,0.15)" : "transparent",
                  color: mode === m ? "var(--accent)" : "var(--text-muted)",
                  textTransform: "uppercase",
                }}
              >
                {m}
              </button>
            ))}
            <div style={{ width: "1px", background: "var(--border)", margin: "0 4px" }} />
            {(["M3", "M4"] as const).map((pm) => (
              <button
                key={pm}
                onClick={() => setPowerMode(pm)}
                title={pm === "M3" ? "Constant power" : "Variable power (laser mode)"}
                style={{
                  flex: 1,
                  padding: "4px 8px",
                  borderRadius: "var(--radius-sm)",
                  fontSize: "11px",
                  fontWeight: 600,
                  cursor: "pointer",
                  border: `1px solid ${powerMode === pm ? "var(--accent)" : "var(--border)"}`,
                  background: powerMode === pm ? "rgba(74,144,226,0.15)" : "transparent",
                  color: powerMode === pm ? "var(--accent)" : "var(--text-muted)",
                  textTransform: "uppercase",
                }}
              >
                {pm === "M3" ? "M3 Const" : "M4 Var"}
              </button>
            ))}
          </div>
        </div>

        {/* Grid size info */}
        <div style={{
          fontSize: "10px",
          color: exceedsWorkspace ? "var(--danger)" : "var(--text-muted)",
          marginBottom: "12px",
        }}>
          Grid: {powerSteps} x {speedSteps} = {powerSteps * speedSteps} cells,
          {" "}{totalWidth.toFixed(0)} x {totalHeight.toFixed(0)} mm
          {exceedsWorkspace && " -- exceeds workspace!"}
        </div>

        {/* Actions */}
        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
          <button
            onClick={() => handleGenerate("send")}
            disabled={jobRunning}
            title={jobRunning ? "Cannot start while a job is running" : undefined}
            style={{
              flex: "1 1 auto",
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "none",
              fontSize: "11px",
              fontWeight: 600,
              cursor: jobRunning ? "not-allowed" : "pointer",
              background: "rgba(74,226,138,0.2)",
              color: "var(--success)",
              opacity: jobRunning ? 0.4 : 1,
            }}
          >
            Send to Machine
          </button>
          <button
            onClick={handleFrame}
            disabled={jobRunning}
            title={jobRunning ? "Cannot frame while a job is running" : "Trace the grid outline without firing the laser"}
            style={{
              flex: "1 1 auto",
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              fontWeight: 600,
              cursor: jobRunning ? "not-allowed" : "pointer",
              background: "transparent",
              color: "var(--text-secondary)",
              opacity: jobRunning ? 0.4 : 1,
            }}
          >
            Frame
          </button>
          <button
            onClick={() => handleGenerate("clipboard")}
            style={{
              flex: "1 1 auto",
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              fontWeight: 600,
              cursor: "pointer",
              background: "transparent",
              color: "var(--text-secondary)",
            }}
          >
            Copy G-code
          </button>
          <button
            onClick={onClose}
            style={{
              padding: "6px 12px",
              borderRadius: "var(--radius-sm)",
              border: "1px solid var(--border)",
              fontSize: "11px",
              cursor: "pointer",
              background: "transparent",
              color: "var(--text-muted)",
            }}
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
}
