use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PathSegment {
    pub points: Vec<Point>,
    pub closed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CutLayer {
    pub mode: String,        // "line", "fill", "offsetFill"
    pub power: f64,          // 0-100
    pub power_min: f64,      // 0-100
    pub speed: f64,          // mm/s
    pub passes: u32,
    pub power_mode: String,  // "constant" or "variable"
    pub interval: f64,       // mm - line interval for fill
    pub air_assist: bool,
    pub cut_inner_first: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CutObject {
    pub id: String,
    pub obj_type: String,    // "rectangle", "ellipse", "line", "path"
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    pub paths: Vec<PathSegment>,
    pub layer: CutLayer,
    pub corner_radius: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GcodeMove {
    pub x: f64,
    pub y: f64,
    pub move_type: String,   // "rapid", "cut", "engrave"
    pub speed: f64,          // mm/min (GRBL uses mm/min)
    pub power: f64,          // 0-1000 (S value)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GcodeResult {
    pub gcode: String,
    pub moves: Vec<GcodeMove>,
    pub total_distance: f64,       // mm
    pub cut_distance: f64,         // mm
    pub travel_distance: f64,      // mm
    pub estimated_time_secs: f64,
    pub line_count: usize,
}

/// Generate G-code from a list of objects with their layer settings
pub fn generate_gcode(objects: &[CutObject], workspace_height: f64) -> GcodeResult {
    let mut lines: Vec<String> = Vec::new();
    let mut moves: Vec<GcodeMove> = Vec::new();
    let mut total_distance = 0.0_f64;
    let mut cut_distance = 0.0_f64;
    let mut travel_distance = 0.0_f64;
    let mut cur_x = 0.0_f64;
    let mut cur_y = 0.0_f64;

    // Header
    lines.push("; Generated by Kerf".to_string());
    lines.push("G21 ; mm mode".to_string());
    lines.push("G90 ; absolute positioning".to_string());
    lines.push("M5 ; laser off".to_string());
    lines.push("G0 X0 Y0 ; home".to_string());
    lines.push(String::new());

    // Sort objects: process by layer priority, inner shapes first within each layer
    let mut sorted_objects = objects.to_vec();
    sorted_objects.sort_by(|a, b| {
        // Inner first: smaller area first
        let area_a = a.width * a.height;
        let area_b = b.width * b.height;
        area_a.partial_cmp(&area_b).unwrap_or(std::cmp::Ordering::Equal)
    });

    for obj in &sorted_objects {
        let layer = &obj.layer;
        let speed_mm_min = layer.speed * 60.0; // Convert mm/s to mm/min
        let s_max = (layer.power / 100.0 * 1000.0).round();
        let _s_min = (layer.power_min / 100.0 * 1000.0).round();

        // Power mode command
        let power_cmd = if layer.power_mode == "variable" { "M4" } else { "M3" };

        for pass in 0..layer.passes {
            if layer.passes > 1 {
                lines.push(format!("; Pass {}/{}", pass + 1, layer.passes));
            }

            match layer.mode.as_str() {
                "line" => {
                    // Vector cut mode
                    lines.push(format!("; Cut: {} ({}% @ {}mm/s)", obj.id, layer.power, layer.speed));

                    let paths = if obj.paths.is_empty() {
                        // Generate path from object geometry
                        vec![object_to_path(obj)]
                    } else {
                        obj.paths.clone()
                    };

                    for path in &paths {
                        if path.points.is_empty() { continue; }

                        // Rapid move to start
                        let start = &path.points[0];
                        let sx = start.x;
                        let sy = workspace_height - start.y; // Flip Y for GRBL
                        let dist = ((sx - cur_x).powi(2) + (sy - cur_y).powi(2)).sqrt();
                        travel_distance += dist;
                        total_distance += dist;

                        lines.push(format!("G0 X{:.3} Y{:.3}", sx, sy));
                        moves.push(GcodeMove {
                            x: sx, y: sy,
                            move_type: "rapid".to_string(),
                            speed: 3000.0, power: 0.0,
                        });
                        cur_x = sx;
                        cur_y = sy;

                        // Turn laser on
                        lines.push(format!("{} S{}", power_cmd, s_max));

                        // Cut along path
                        for i in 1..path.points.len() {
                            let pt = &path.points[i];
                            let px = pt.x;
                            let py = workspace_height - pt.y;
                            let d = ((px - cur_x).powi(2) + (py - cur_y).powi(2)).sqrt();
                            cut_distance += d;
                            total_distance += d;

                            lines.push(format!("G1 X{:.3} Y{:.3} F{:.0} S{}", px, py, speed_mm_min, s_max));
                            moves.push(GcodeMove {
                                x: px, y: py,
                                move_type: "cut".to_string(),
                                speed: speed_mm_min, power: s_max,
                            });
                            cur_x = px;
                            cur_y = py;
                        }

                        // Close path if needed
                        if path.closed && path.points.len() > 2 {
                            let first = &path.points[0];
                            let fx = first.x;
                            let fy = workspace_height - first.y;
                            let d = ((fx - cur_x).powi(2) + (fy - cur_y).powi(2)).sqrt();
                            cut_distance += d;
                            total_distance += d;

                            lines.push(format!("G1 X{:.3} Y{:.3} F{:.0} S{}", fx, fy, speed_mm_min, s_max));
                            moves.push(GcodeMove {
                                x: fx, y: fy,
                                move_type: "cut".to_string(),
                                speed: speed_mm_min, power: s_max,
                            });
                            cur_x = fx;
                            cur_y = fy;
                        }

                        // Laser off
                        lines.push("M5".to_string());
                    }
                }
                "fill" | "offsetFill" => {
                    // Raster engrave mode
                    lines.push(format!("; Engrave: {} ({}% @ {}mm/s, interval {}mm)",
                        obj.id, layer.power, layer.speed, layer.interval));

                    let interval = if layer.interval > 0.0 { layer.interval } else { 0.1 };
                    let x_min = obj.x;
                    let x_max = obj.x + obj.width;
                    let y_min = obj.y;
                    let y_max = obj.y + obj.height;

                    let mut y = y_min;
                    let mut left_to_right = true;

                    while y <= y_max {
                        let gy = workspace_height - y; // Flip Y

                        // Move to start of scan line
                        let (sx, ex) = if left_to_right {
                            (x_min, x_max)
                        } else {
                            (x_max, x_min)
                        };

                        // Rapid to scan start
                        let dist = ((sx - cur_x).powi(2) + (gy - cur_y).powi(2)).sqrt();
                        travel_distance += dist;
                        total_distance += dist;
                        lines.push(format!("G0 X{:.3} Y{:.3}", sx, gy));
                        moves.push(GcodeMove {
                            x: sx, y: gy,
                            move_type: "rapid".to_string(),
                            speed: 3000.0, power: 0.0,
                        });

                        // Engrave scan line
                        lines.push(format!("{} S{}", power_cmd, s_max));
                        let scan_dist = (ex - sx).abs();
                        cut_distance += scan_dist;
                        total_distance += scan_dist;
                        lines.push(format!("G1 X{:.3} Y{:.3} F{:.0} S{}", ex, gy, speed_mm_min, s_max));
                        moves.push(GcodeMove {
                            x: ex, y: gy,
                            move_type: "engrave".to_string(),
                            speed: speed_mm_min, power: s_max,
                        });
                        lines.push("M5".to_string());
                        cur_x = ex;
                        cur_y = gy;

                        y += interval;
                        left_to_right = !left_to_right;
                    }
                }
                _ => {}
            }

            lines.push(String::new());
        }
    }

    // Footer
    lines.push("M5 ; laser off".to_string());
    lines.push("G0 X0 Y0 ; return home".to_string());
    lines.push("M2 ; program end".to_string());

    // Time estimation
    // Account for acceleration: assume 200mm/s^2 default GRBL accel
    let accel = 200.0_f64; // mm/s^2
    let estimated_time = estimate_time(&moves, accel);

    GcodeResult {
        gcode: lines.join("\n"),
        moves,
        total_distance,
        cut_distance,
        travel_distance,
        estimated_time_secs: estimated_time,
        line_count: lines.len(),
    }
}

/// Convert object geometry to a path
fn object_to_path(obj: &CutObject) -> PathSegment {
    match obj.obj_type.as_str() {
        "rectangle" => {
            let x = obj.x;
            let y = obj.y;
            let w = obj.width;
            let h = obj.height;

            if let Some(r) = obj.corner_radius {
                if r > 0.0 {
                    // Rounded rectangle approximation
                    let r = r.min(w / 2.0).min(h / 2.0);
                    let mut points = Vec::new();
                    // Top edge (left to right)
                    points.push(Point { x: x + r, y });
                    points.push(Point { x: x + w - r, y });
                    // Top-right corner
                    arc_points(&mut points, x + w - r, y + r, r, -90.0, 0.0, 8);
                    // Right edge
                    points.push(Point { x: x + w, y: y + h - r });
                    // Bottom-right corner
                    arc_points(&mut points, x + w - r, y + h - r, r, 0.0, 90.0, 8);
                    // Bottom edge
                    points.push(Point { x: x + r, y: y + h });
                    // Bottom-left corner
                    arc_points(&mut points, x + r, y + h - r, r, 90.0, 180.0, 8);
                    // Left edge
                    points.push(Point { x, y: y + r });
                    // Top-left corner
                    arc_points(&mut points, x + r, y + r, r, 180.0, 270.0, 8);

                    return PathSegment { points, closed: true };
                }
            }

            PathSegment {
                points: vec![
                    Point { x, y },
                    Point { x: x + w, y },
                    Point { x: x + w, y: y + h },
                    Point { x, y: y + h },
                ],
                closed: true,
            }
        }
        "ellipse" => {
            let cx = obj.x + obj.width / 2.0;
            let cy = obj.y + obj.height / 2.0;
            let rx = obj.width / 2.0;
            let ry = obj.height / 2.0;
            let segments = 64;
            let mut points = Vec::with_capacity(segments);
            for i in 0..segments {
                let angle = 2.0 * std::f64::consts::PI * (i as f64) / (segments as f64);
                points.push(Point {
                    x: cx + rx * angle.cos(),
                    y: cy + ry * angle.sin(),
                });
            }
            PathSegment { points, closed: true }
        }
        "line" => {
            PathSegment {
                points: vec![
                    Point { x: obj.x, y: obj.y },
                    Point { x: obj.x + obj.width, y: obj.y + obj.height },
                ],
                closed: false,
            }
        }
        _ => PathSegment { points: vec![], closed: false },
    }
}

/// Generate arc points for rounded corners
fn arc_points(points: &mut Vec<Point>, cx: f64, cy: f64, r: f64, start_deg: f64, end_deg: f64, segments: usize) {
    let start_rad = start_deg.to_radians();
    let end_rad = end_deg.to_radians();
    for i in 0..=segments {
        let t = i as f64 / segments as f64;
        let angle = start_rad + (end_rad - start_rad) * t;
        points.push(Point {
            x: cx + r * angle.cos(),
            y: cy + r * angle.sin(),
        });
    }
}

/// Estimate job time accounting for acceleration curves
fn estimate_time(moves: &[GcodeMove], accel: f64) -> f64 {
    let mut total_time = 0.0_f64;
    let mut prev_x = 0.0_f64;
    let mut prev_y = 0.0_f64;

    for m in moves {
        let dist = ((m.x - prev_x).powi(2) + (m.y - prev_y).powi(2)).sqrt();
        if dist < 0.001 {
            prev_x = m.x;
            prev_y = m.y;
            continue;
        }

        let max_speed = m.speed / 60.0; // mm/min to mm/s

        // Time with trapezoidal acceleration profile
        // Distance to accelerate to max speed: d = v^2 / (2*a)
        let accel_dist = max_speed * max_speed / (2.0 * accel);

        if dist < 2.0 * accel_dist {
            // Triangle profile: never reaches max speed
            // t = 2 * sqrt(d / a)
            total_time += 2.0 * (dist / accel).sqrt();
        } else {
            // Trapezoidal: accel + cruise + decel
            let accel_time = max_speed / accel;
            let cruise_dist = dist - 2.0 * accel_dist;
            let cruise_time = cruise_dist / max_speed;
            total_time += 2.0 * accel_time + cruise_time;
        }

        prev_x = m.x;
        prev_y = m.y;
    }

    total_time
}
