; Generated by Kerf
G21 ; mm mode
G90 ; absolute positioning
M5 ; laser off
G0 X0 Y0 ; home
; KERF:PREAMBLE_END

; Cut: rect (80% @ 1200mm/min)
G0 X10.000 Y290.000
M3 S800
G1 X40.000 Y290.000 F1200 S800
G1 X40.000 Y270.000 F1200 S800
G1 X10.000 Y270.000 F1200 S800
G1 X10.000 Y290.000 F1200 S800
M5

; KERF:FOOTER_BEGIN
M5 ; laser off
G0 X0 Y0 ; return home
M2 ; program end
