; Generated by Kerf
G21 ; mm mode
G90 ; absolute positioning
M5 ; laser off
G0 X0 Y0 ; home
; KERF:PREAMBLE_END

; Cut: rotated (90% @ 1500mm/min)
G0 X3.840 Y84.330
M3 S900
G1 X21.160 Y74.330 F1500 S900
G1 X16.160 Y65.670 F1500 S900
G1 X-1.160 Y75.670 F1500 S900
G1 X3.840 Y84.330 F1500 S900
M5

; KERF:FOOTER_BEGIN
M5 ; laser off
G0 X0 Y0 ; return home
M2 ; program end
