; Generated by Kerf
G21 ; mm mode
G90 ; absolute positioning
M5 ; laser off
G0 X0 Y0 ; home
; KERF:PREAMBLE_END

; Cut: var_sq (40% @ 1200mm/min)
G0 X0.000 Y100.000
M4 S400
G1 X30.000 Y100.000 F1200 S400
G1 X30.000 Y80.000 F1200 S400
G1 X0.000 Y80.000 F1200 S400
G1 X0.000 Y100.000 F1200 S400
M5

; KERF:FOOTER_BEGIN
M5 ; laser off
G0 X0 Y0 ; return home
M2 ; program end
