import { invoke } from "@tauri-apps/api/core";
import { useStore } from "../../app/store";
import type { DesignObject, Layer } from "../../app/types";

export interface GcodeMove {
  x: number;
  y: number;
  moveType: "rapid" | "cut" | "engrave";
  speed: number;
  power: number;
}

export interface GcodeResult {
  gcode: string;
  moves: GcodeMove[];
  totalDistance: number;
  cutDistance: number;
  travelDistance: number;
  estimatedTimeSecs: number;
  lineCount: number;
}

interface CutObject {
  id: string;
  objType: string;
  x: number;
  y: number;
  width: number;
  height: number;
  paths: Array<{ points: Array<{ x: number; y: number }>; closed: boolean }>;
  layer: {
    mode: string;
    power: number;
    powerMin: number;
    speed: number;
    passes: number;
    powerMode: string;
    interval: number;
    airAssist: boolean;
    cutInnerFirst: boolean;
  };
  cornerRadius: number | null;
}

/** Convert store objects to CutObjects for the Rust engine */
function toCutObjects(objects: DesignObject[], layers: Layer[]): CutObject[] {
  return objects
    .filter((obj) => obj.visible && !obj.locked && obj.type !== "text" && obj.type !== "image")
    .map((obj) => {
      const layer = layers.find((l) => l.index === obj.layerIndex) || layers[0];
      const paths: CutObject["paths"] = [];

      if (obj.points && obj.points.length >= 2) {
        paths.push({
          points: obj.points.map((p) => ({ x: p.x, y: p.y })),
          closed: obj.closed || false,
        });
      }

      return {
        id: obj.id,
        objType: obj.type,
        x: obj.transform.x,
        y: obj.transform.y,
        width: obj.transform.width,
        height: obj.transform.height,
        paths,
        layer: {
          mode: layer.mode,
          power: layer.power,
          powerMin: layer.powerMin,
          speed: layer.speed,
          passes: layer.passes,
          powerMode: layer.powerMode,
          interval: layer.interval,
          airAssist: layer.airAssist,
          cutInnerFirst: layer.cutInnerFirst,
        },
        cornerRadius: obj.cornerRadius || null,
      };
    });
}

/** Generate G-code from the current design using Rust backend */
export async function generateGcode(): Promise<GcodeResult> {
  const store = useStore.getState();
  const cutObjects = toCutObjects(store.objects, store.layers);

  try {
    const result = await invoke<GcodeResult>("generate_gcode", {
      objects: cutObjects,
      workspaceHeight: store.workspaceHeight,
    });
    return result;
  } catch (e) {
    // Fallback: generate G-code in JS if Rust isn't available
    console.warn("Rust G-code gen failed, using JS fallback:", e);
    return generateGcodeFallback(cutObjects, store.workspaceHeight);
  }
}

/** Pure JS fallback G-code generator */
function generateGcodeFallback(objects: CutObject[], workspaceHeight: number): GcodeResult {
  const lines: string[] = [];
  const moves: GcodeMove[] = [];
  let cutDist = 0;
  let travelDist = 0;
  let cx = 0, cy = 0;

  lines.push("; Generated by Kerf");
  lines.push("G21 ; mm mode");
  lines.push("G90 ; absolute positioning");
  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0");
  lines.push("");

  for (const obj of objects) {
    const speed = obj.layer.speed * 60; // mm/s to mm/min
    const sMax = Math.round(obj.layer.power / 100 * 1000);
    const powerCmd = obj.layer.powerMode === "variable" ? "M4" : "M3";

    for (let pass = 0; pass < obj.layer.passes; pass++) {
      if (obj.layer.mode === "line") {
        const pts = obj.paths.length > 0 ? obj.paths[0].points : objectToPoints(obj);
        const closed = obj.paths.length > 0 ? obj.paths[0].closed : (obj.objType !== "line");

        if (pts.length < 2) continue;

        // Rapid to start
        const sy = workspaceHeight - pts[0].y;
        const d = Math.hypot(pts[0].x - cx, sy - cy);
        travelDist += d;
        lines.push(`G0 X${pts[0].x.toFixed(3)} Y${sy.toFixed(3)}`);
        moves.push({ x: pts[0].x, y: sy, moveType: "rapid", speed: 3000, power: 0 });
        cx = pts[0].x; cy = sy;

        lines.push(`${powerCmd} S${sMax}`);

        for (let i = 1; i < pts.length; i++) {
          const py = workspaceHeight - pts[i].y;
          const dd = Math.hypot(pts[i].x - cx, py - cy);
          cutDist += dd;
          lines.push(`G1 X${pts[i].x.toFixed(3)} Y${py.toFixed(3)} F${speed} S${sMax}`);
          moves.push({ x: pts[i].x, y: py, moveType: "cut", speed, power: sMax });
          cx = pts[i].x; cy = py;
        }

        if (closed && pts.length > 2) {
          const fy = workspaceHeight - pts[0].y;
          const dd = Math.hypot(pts[0].x - cx, fy - cy);
          cutDist += dd;
          lines.push(`G1 X${pts[0].x.toFixed(3)} Y${fy.toFixed(3)} F${speed} S${sMax}`);
          moves.push({ x: pts[0].x, y: fy, moveType: "cut", speed, power: sMax });
          cx = pts[0].x; cy = fy;
        }

        lines.push("M5");
      } else {
        // Fill mode
        const interval = obj.layer.interval || 0.1;
        let y = obj.y;
        let ltr = true;

        while (y <= obj.y + obj.height) {
          const gy = workspaceHeight - y;
          const sx = ltr ? obj.x : obj.x + obj.width;
          const ex = ltr ? obj.x + obj.width : obj.x;

          travelDist += Math.hypot(sx - cx, gy - cy);
          lines.push(`G0 X${sx.toFixed(3)} Y${gy.toFixed(3)}`);
          moves.push({ x: sx, y: gy, moveType: "rapid", speed: 3000, power: 0 });

          lines.push(`${powerCmd} S${sMax}`);
          cutDist += Math.abs(ex - sx);
          lines.push(`G1 X${ex.toFixed(3)} Y${gy.toFixed(3)} F${speed} S${sMax}`);
          moves.push({ x: ex, y: gy, moveType: "engrave", speed, power: sMax });
          lines.push("M5");

          cx = ex; cy = gy;
          y += interval;
          ltr = !ltr;
        }
      }
      lines.push("");
    }
  }

  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0 ; return home");
  lines.push("M2 ; program end");

  const totalDist = cutDist + travelDist;

  // Basic time estimate
  let time = 0;
  for (const m of moves) {
    const prev = moves.indexOf(m) > 0 ? moves[moves.indexOf(m) - 1] : { x: 0, y: 0 };
    const d = Math.hypot(m.x - prev.x, m.y - prev.y);
    time += d / (m.speed / 60); // speed is mm/min
  }

  return {
    gcode: lines.join("\n"),
    moves,
    totalDistance: totalDist,
    cutDistance: cutDist,
    travelDistance: travelDist,
    estimatedTimeSecs: time,
    lineCount: lines.length,
  };
}

function objectToPoints(obj: CutObject): Array<{ x: number; y: number }> {
  switch (obj.objType) {
    case "rectangle":
      return [
        { x: obj.x, y: obj.y },
        { x: obj.x + obj.width, y: obj.y },
        { x: obj.x + obj.width, y: obj.y + obj.height },
        { x: obj.x, y: obj.y + obj.height },
      ];
    case "ellipse": {
      const cxe = obj.x + obj.width / 2;
      const cye = obj.y + obj.height / 2;
      const rx = obj.width / 2;
      const ry = obj.height / 2;
      const pts: Array<{ x: number; y: number }> = [];
      for (let i = 0; i < 64; i++) {
        const a = (2 * Math.PI * i) / 64;
        pts.push({ x: cxe + rx * Math.cos(a), y: cye + ry * Math.sin(a) });
      }
      return pts;
    }
    case "line":
      return [
        { x: obj.x, y: obj.y },
        { x: obj.x + obj.width, y: obj.y + obj.height },
      ];
    default:
      return [];
  }
}
