import { textToGcode } from "./textGcode";

export type PowerMode = "M3" | "M4";

export interface MaterialTestOptions {
  powerMin: number;
  powerMax: number;
  powerSteps: number;
  speedMin: number;
  speedMax: number;
  speedSteps: number;
  cellWidth: number;
  cellHeight: number;
  cellGap: number;
  mode: "cut" | "fill";
  powerMode: PowerMode;
  labels: boolean;
  cutBorder: boolean;
}

export async function generateMaterialTestGcode(
  opts: MaterialTestOptions,
  sValueMax: number
): Promise<string> {
  const lines: string[] = [];
  lines.push("; Material Test Grid -- Generated by Kerf");
  lines.push("G21 ; mm mode");
  lines.push("G90 ; absolute positioning");
  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0");
  lines.push("");

  const powers: number[] = [];
  for (let i = 0; i < opts.powerSteps; i++) {
    powers.push(
      opts.powerSteps === 1
        ? opts.powerMin
        : opts.powerMin + (opts.powerMax - opts.powerMin) * (i / (opts.powerSteps - 1))
    );
  }

  const speeds: number[] = [];
  for (let i = 0; i < opts.speedSteps; i++) {
    speeds.push(
      opts.speedSteps === 1
        ? opts.speedMin
        : opts.speedMin + (opts.speedMax - opts.speedMin) * (i / (opts.speedSteps - 1))
    );
  }

  const labelMargin = opts.labels ? 5 : 0;
  const startX = 10 + labelMargin;
  const startY = 10 + labelMargin;

  // Column headers (speed values) — real text engraved above the grid
  if (opts.labels) {
    const labelS = Math.round(sValueMax * 0.12);
    const labelFeed = 3000;

    lines.push("; --- Column headers (speed) ---");
    for (let si = 0; si < speeds.length; si++) {
      const speed = Math.round(speeds[si]);
      const cx = startX + si * (opts.cellWidth + opts.cellGap);
      const ly = startY - 4; // 4mm above the grid — enough room for 2.5mm glyphs
      const labelLines = await textToGcode(
        `${speed}`,
        cx,
        ly,
        2.5,
        labelS,
        labelFeed,
        opts.powerMode
      );
      lines.push(...labelLines);
    }

    lines.push("; --- Row headers (power) ---");
    for (let pi = 0; pi < powers.length; pi++) {
      const power = Math.round(powers[pi]);
      const cy = startY + pi * (opts.cellHeight + opts.cellGap);
      const lx = startX - labelMargin; // left of the grid
      const labelLines = await textToGcode(
        `${power}%`,
        lx,
        cy + opts.cellHeight / 2 - 1,
        2.5,
        labelS,
        labelFeed,
        opts.powerMode
      );
      lines.push(...labelLines);
    }

    lines.push("");
  }

  for (let pi = 0; pi < powers.length; pi++) {
    for (let si = 0; si < speeds.length; si++) {
      const power = Math.round(powers[pi]);
      const speed = Math.round(speeds[si]);
      const sValue = Math.round((power / 100) * sValueMax);
      const feedRate = speed; // speed is already mm/min

      const cx = startX + si * (opts.cellWidth + opts.cellGap);
      // Y is inverted in G-code (origin bottom-left)
      const cy = startY + pi * (opts.cellHeight + opts.cellGap);

      lines.push(`; Cell P${power}% S${speed}mm/min`);

      if (opts.mode === "cut") {
        // Rectangle outline — power on once, off once
        lines.push(`G0 X${cx.toFixed(3)} Y${cy.toFixed(3)}`);
        lines.push(`${opts.powerMode} S${sValue}`);
        lines.push(
          `G1 X${(cx + opts.cellWidth).toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`
        );
        lines.push(
          `G1 X${(cx + opts.cellWidth).toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`
        );
        lines.push(
          `G1 X${cx.toFixed(3)} Y${(cy + opts.cellHeight).toFixed(3)} F${feedRate} S${sValue}`
        );
        lines.push(`G1 X${cx.toFixed(3)} Y${cy.toFixed(3)} F${feedRate} S${sValue}`);
        lines.push("M5");
      } else {
        // Filled rectangle — continuous bidirectional sweep.
        // Power on ONCE before all scan lines, M5 ONCE after, no G0 between lines.
        // This eliminates the per-line M4/M5 accel spike pattern.
        const interval = 0.1;
        let forward = true;
        let y = cy;

        // Lead-in: position before power-on
        lines.push(`G0 X${cx.toFixed(3)} Y${y.toFixed(3)}`);
        lines.push(`${opts.powerMode} S${sValue}`);

        while (y <= cy + opts.cellHeight + 1e-9) {
          const ex = forward ? cx + opts.cellWidth : cx;
          lines.push(`G1 X${ex.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          y += interval;
          if (y <= cy + opts.cellHeight + 1e-9) {
            // Step to next line at feed rate (no G0, no M5 — continuous beam)
            forward = !forward;
            const nextX = forward ? cx : cx + opts.cellWidth;
            lines.push(`G1 X${nextX.toFixed(3)} Y${y.toFixed(3)} F${feedRate} S${sValue}`);
          } else {
            forward = !forward;
          }
        }

        lines.push("M5");
      }
      lines.push("");
    }
  }

  // Cut border — surrounds the entire grid for a reusable test card
  if (opts.cutBorder) {
    const gridW = opts.speedSteps * (opts.cellWidth + opts.cellGap) - opts.cellGap;
    const gridH = opts.powerSteps * (opts.cellHeight + opts.cellGap) - opts.cellGap;
    const margin = 3;
    const bx = startX - margin - labelMargin;
    const by = startY - margin - labelMargin;
    const bw = gridW + 2 * margin + labelMargin;
    const bh = gridH + 2 * margin + labelMargin;
    const borderS = sValueMax;
    const borderFeed = 200;
    lines.push("; --- Cut border (reusable test card) ---");
    lines.push(`G0 X${bx.toFixed(3)} Y${by.toFixed(3)}`);
    lines.push(`M3 S${borderS}`);
    lines.push(`G1 X${(bx + bw).toFixed(3)} Y${by.toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push(`G1 X${(bx + bw).toFixed(3)} Y${(by + bh).toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push(`G1 X${bx.toFixed(3)} Y${(by + bh).toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push(`G1 X${bx.toFixed(3)} Y${by.toFixed(3)} F${borderFeed} S${borderS}`);
    lines.push("M5");
    lines.push("");
  }

  lines.push("M5 ; laser off");
  lines.push("G0 X0 Y0 ; return home");
  lines.push("M2 ; program end");

  return lines.join("\n");
}

export function generateFrameGcode(totalWidth: number, totalHeight: number): string {
  const lines: string[] = [];
  lines.push("; Frame trace -- laser off");
  lines.push("G21");
  lines.push("G90");
  lines.push("M5");
  lines.push("G0 X10 Y10");
  lines.push(`G1 X${(10 + totalWidth).toFixed(3)} Y10 F3000`);
  lines.push(`G1 X${(10 + totalWidth).toFixed(3)} Y${(10 + totalHeight).toFixed(3)} F3000`);
  lines.push(`G1 X10 Y${(10 + totalHeight).toFixed(3)} F3000`);
  lines.push("G1 X10 Y10 F3000");
  lines.push("G0 X0 Y0");
  return lines.join("\n");
}
